# Generated by Django 2.1.7 on 2019-04-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='votes',
        ),
    ]
